### ISSUE TITLE
Inference of the training

### ISSUE THREAD

**Issue by sanjanagovind** [SunghwanHong/Cost-Aggregation-transformers#10]
Is it possible to take the inference of your pretrained model on any novel image ? if yes, please provide the inference code ?

**Comment by SunghwanHong** [comment]
Yes, you can do it. 
Currently, we are not planning to provide an inference code for custom dataset or images. 
However, you can refer to https://github.com/PruneTruong/DenseMatching, where organized codes are available with easy-to-follow instructions
