### ISSUE TITLE
release of pre-trained weights

### ISSUE THREAD

**Issue by Tsingularity** [SunghwanHong/Cost-Aggregation-transformers#13]
Hi thanks for the great work! 

Just wondering when do you plan to release the pre-trained weights? It seems that link cannot be open. 

Thanks!

**Comment by SunghwanHong** [comment]
Oh sorry,
I will let you know after I fix the link.

**Comment by Tsingularity** [comment]
Thanks! Looking forward to it!

**Comment by SunghwanHong** [comment]
It's there ! Thanks for your patience!
