### ISSUE TITLE
Visualization results

### ISSUE THREAD

**Issue by Acero522** [SunghwanHong/Cost-Aggregation-transformers#7]
Hi,Thanks for your great work. I want to see the Visualization results of it. How can I draw images of correspondence between 2 images like Figure 5 in your paper. Do you have code for that? Thanks!

**Comment by SunghwanHong** [comment]
Hi,
im so sorry for keeping you wait
I was super busy recently and made you wait this long. 
Sure, i will upload the visualization code tomorrow when i arrive my lab. 

Again, thanks for your interest in our research and sorry for keeping you wait

**Comment by geovsion** [comment]
Sorry, I don't seem to see the uploaded visual code, could you please send me a copy? Thank you

**Comment by Acero522** [comment]
He didn't send me or upload the code later, sorry.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunghwanHong/Cost-Aggregation-transformers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 上午10:09
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [SunghwanHong/Cost-Aggregation-transformers] Visualization results (Issue #7)





 
Sorry, I don't seem to see the uploaded visual code, could you please send me a copy? Thank you
