### ISSUE TITLE
Data download error.

### ISSUE THREAD

**Issue by SirojbekSafarov** [SunghwanHong/Cost-Aggregation-transformers#8]
Hi, thanks for the great work! 

When I run the train.py, the data did not downloaded. 
I got tarfile.ReadError: not a gzip file error.

Can you give dataset links that we can download manually?

Thank you!

**Comment by Rongyimin-z** [comment]
> 

http://cvlab.postech.ac.kr/research/SPair-71k/  At the bottom of the page, this might help you

**Comment by SunghwanHong** [comment]
Oh hi,
Sorry for the late reply. 
It seems like the link is already given..!
Thanks!
